curl --request POST \
     --url http://144.126.209.213:8803/invoke/sertifikat/chaincode-sertifikat \
     --Access-Control-Allow-Origin: * \
     --header 'Authorization: Bearer {token}' \
     --data '{
        "method": "CreateAsset",
        "args": [
            "M-SMK/06-3/0000213",
            "0054723235",
            "2021.10.1005",
            "Ahyar Maulidin",
            "Laki-laki",
            "Teknik Komputer & Jaringan",
            "bafybeiagevvnocxpg232abu2hmnlvriv3jjysojcierrsyypcyeygticcq",
            "Dikonfirmasi",
            "Dikonfirmasi"
        ]
     }'

curl --request POST \
     --url http://144.126.209.213:8803/invoke/sertifikat/chaincode-sertifikat \
     --Access-Control-Allow-Origin: * \
     --header 'Authorization: Bearer 9b0ef0b0-31c5-11ee-9409-33514e3d0d9a-admin' \
     --data '{
        "method": "UpdateAsset",
        "args": [
            "M-SMK/06-3/0000213",
            "0054723235",
            "2021.10.1005",
            "Ahyar Maulidin",
            "Laki-laki",
            "Teknik Komputer & Jaringan",
            "bafybeiagevvnocxpg232abu2hmnlvriv3jjysojcierrsyypcyeygticcq",
            "Dikonfirmasi",
            "Dikonfirmasi"
        ]
     }'

curl --request POST \
     --url http://144.126.209.213:8803/invoke/sertifikat/chaincode-sertifikat \
     --Access-Control-Allow-Origin: * \
     --header 'Authorization: Bearer 9b0ef0b0-31c5-11ee-9409-33514e3d0d9a-admin' \
     --data '{
        "method": "GetAllAssets",
        "args": []
     }'

curl --request POST \
     --url http://144.126.209.213:8803/invoke/sertifikat/chaincode-sertifikat \
     --Access-Control-Allow-Origin: * \
     --header 'Authorization: Bearer 9b0ef0b0-31c5-11ee-9409-33514e3d0d9a-admin' \
     --data '{
        "method": "DeletAsset",
        "args": [
            "{no_sertifikat}"
        ]
     }'